name: build

on:
  push:
    paths-ignore:
    - '**/*.pdf'
    - '**/README.md'
  pull_request:
    paths-ignore:
    - '**/*.pdf'
    - '**/README.md'

jobs:
  popl2022:
    runs-on: ubuntu-18.04
    steps:
    - uses: actions/checkout@v2
      with:
        submodules: true
    - uses: dante-ev/latex-action@latest
      with:
        entrypoint: ./popl2022/build.sh
