name: paper-builds

on:
  push:
    paths-ignore:
    - '**/*.pdf'
    - '**/README.md'
  pull_request:
    paths-ignore:
    - '**/*.pdf'
    - '**/README.md'

jobs:
  popl2022:
    runs-on: ubuntu-18.04
    steps:
    - uses: nanasess/setup-chromedriver@v1.0.1
    - uses: browser-actions/setup-chrome@latest
    - uses: actions/checkout@v2
      with:
        submodules: true
    - name: collate-examples
      run: |
        source collate-examples.sh
    - uses: dante-ev/latex-action@latest
      with:
        entrypoint: ./all-versions.sh
    - uses: actions/upload-artifact@v2
      with:
        path: ./anonymised.pdf
