name: build

on:
  push:
    paths-ignore:
    - '**/*.pdf'
    - '**/README.md'
  pull_request:
    paths-ignore:
    - '**/*.pdf'
    - '**/README.md'

jobs:
  popl2022:
    runs-on: ubuntu-18.04
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    steps:
    - uses: actions/checkout@v2
      with:
        submodules: true
    - uses: dante-ev/latex-action@latest
      with:
        entrypoint: ./popl2022/build.sh
    - uses: rymndhng/release-on-push-action@master
      with:
        bump_version_scheme: minor
    - uses: softprops/action-gh-release@v1
      if: startsWith(github.ref, 'refs/tags/')
      with:
        files: popl2022/main.pdf
