name: build

on:
  push:
    paths-ignore:
    - '**/*.pdf'
    - '**/README.md'
  pull_request:
    paths-ignore:
    - '**/*.pdf'
    - '**/README.md'

jobs:
  popl2022:
    runs-on: windows-latest
    steps:
    - uses: nanasess/setup-chromedriver@v1.0.1
    - uses: browser-actions/setup-chrome@latest
    - uses: actions/checkout@v2
      with:
        submodules: true
    - name: collate-examples
      run: |
        cd popl2022
        source collate-examples.sh
    - uses: dante-ev/latex-action@latest
      with:
        entrypoint: ./popl2022/build.sh
    - uses: actions/upload-artifact@v2
      with:
        path: ./popl2022/main.pdf
